{
  "font": {
    "glyph_offset": {
      "y": 6
    },
    "normal": {
      "family": "JetBrains Mono NL"
    },
    "offset": {
      "y": 12
    },
    "size": 12
  },
  "shell": {
    "program": "zsh"
  },
  "window": {
    "padding": {
      "x": 15,
      "y": 15
    }
  }
}
