---
- name: Install
  community.general.cargo:
    name:
      - starship
    path: /usr/local
    state: latest
  become: true

- name: Config
  ansible.builtin.file:
    src: "{{ role_path }}/files/starship.toml"
    dest: "{{ ansible_user_dir }}/.config/starship.toml"
    state: link
