---
- name: Install
  community.general.npm:
    name: "{{ npm_install_item }}"
    state: latest
    global: true
  loop_control:
    loop_var: npm_install_item
  with_items:
    - "@ansible/ansible-language-server"
    - "@tailwindcss/language-server"
    - bash-language-server
    - dockerfile-language-server-nodejs
    - intelephense
    - typescript
    - typescript-language-server
    - vls
    - vscode-langservers-extracted
    - yaml-language-server
  become: true

- name: Add intelephense licence key
  ansible.builtin.copy:
    content: "{{ intelephense_licence }}"
    dest: "{{ ansible_user_dir }}/intelephense/licence.txt"
    mode: 0400
  no_log: true
  when: intelephense_licence is defined
