---
- hosts: localhost
  roles:
    - role: alacritty
      tags:
        - "skip-if-wsl"
    - role: ctop
    - role: dconf
    - role: docker
    - role: firefox
      tags:
        - "skip-if-wsl"
    - role: fzf
    - role: git
    - role: htop
    - role: lazydocker
    - role: lazygit
    - role: neovim
    - role: nnn
    - role: pv
    - role: rename
    - role: ripgrep
    - role: tmux
    - role: zsh
    - role: zsh-antigen
