---
- name: Install
  ansible.builtin.package:
    name:
      - tmux
    state: latest
  become: true

- name: Directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/tmux"
    state: directory

- name: Configuration
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ ansible_user_dir }}/.config/tmux/tmux.conf"
    state: link
