---
- name: Dependencies
  ansible.builtin.package:
    name: ruby
    state: latest
  become: true

- name: Install
  community.general.gem:
    bindir: "{{ ansible_user_dir }}/.local/bin"
    name: tmuxinator
    state: latest

- name: Configuration
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/tmuxinator"
    state: directory

- name: Copy configuration files
  copy:
    content: "{{ tmuxinator_config_file.value }}"
    dest: "{{ ansible_user_dir }}/.config/tmuxinator/{{ tmuxinator_config_file.key }}.yml"
    mode: 0644
  loop_control:
    loop_var: tmuxinator_config_file
  no_log: true
  with_items: "{{ tmuxinator_config | default({}) | dict2items }}"
