---
- name: Download
  ansible.builtin.get_url:
    dest: "{{ font_item.dest }}"
    url: "{{ font_item.url }}"
  loop_control:
    loop_var: font_item
  loop:
    - url: "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Ligatures/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete%20Mono.ttf?raw=true"
      dest: /usr/share/fonts/truetype/JetBrainsMono Nerd Font Regular

    - url: "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Ligatures/Italic/complete/JetBrains%20Mono%20Italic%20Nerd%20Font%20Complete%20Mono.ttf?raw=true"
      dest: /usr/share/fonts/truetype/JetBrainsMono Nerd Font Italic
  become: true
